# https://www.elastic.co/guide/en/elasticsearch/reference/index.html

cluster.name: cdn-es
node.name: cdn-es-node-3
node.attr.rack: r3
node.master: false

path.data: /home/admin/elk/elasticsearch/datacdn,/mnt/es/data

path.logs: /home/admin/elk/elasticsearch/logs

# ----------------------------------- Memory -----------------------------------
#
# Lock the memory on startup:
#
bootstrap.memory_lock: true
#
# Make sure that the heap size is set to about half the memory available
# on the system and that the owner of the process is allowed to use this
# limit.
#
# Elasticsearch performs poorly when the system is swapping the memory.
#
# ---------------------------------- Network -----------------------------------

network.host: 10.214.162.128
http.port: 9200

# --------------------------------- Discovery ----------------------------------
#
# Pass an initial list of hosts to perform discovery when new node is started:
# The default list of hosts is ["127.0.0.1", "[::1]"]
#
discovery.zen.ping.unicast.hosts: ["10.214.162.79", "10.214.162.77","10.214.162.128"]
#
# Prevent the "split brain" by configuring the majority of nodes (total number of master-eligible nodes / 2 + 1):
#
discovery.zen.minimum_master_nodes: 2 
#
# For more information, consult the zen discovery module documentation.
#
# ---------------------------------- Gateway -----------------------------------
#
# Block initial recovery after a full cluster restart until N nodes are started:
#
gateway.recover_after_nodes: 1
#
# For more information, consult the gateway module documentation.
#
# ---------------------------------- Various -----------------------------------
#
# Require explicit names when deleting indices:
#
action.destructive_requires_name: false

thread_pool:
    bulk:
        size: 9 
        queue_size: 5000

    index:
        size: 8
        queue_size: 3000
